<!doctype html>
<html lang="en" xmlns:ng="http://angularjs.org" ng-app="buiApp">
    <head>
        <title>Beanstalk UI</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, minimum-scale=1.0, initial-scale=1.0, user-scalable=yes">

        <link rel="stylesheet" type="text/css" href="/vendor/bootstrap/dist/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="/vendor/angular-grid/ng-grid.min.css">

        <style type="text/css">
            .gridStyle {
                border: 1px solid rgb(212,212,212);
                width: 100%;
                height: 300px
            }
            #chart {
                height: 400px;
                width: 800px;
            }
        </style>
    </head>
    <body ng-controller="IndexController">
        <h1>Beanstalk UI</h1>

        <div class="gridStyle" ng-grid="gridOptions"></div>

        <div ac-chart="chart.chartType" ac-data="chart.data" ac-config="chart.config" id="chart" class="chart ng-isolate-scope ng-scope"></div>

        <script src="/vendor/jquery/dist/jquery.min.js" type="text/javascript"></script>
        <script src="/vendor/angular/angular.min.js" type="text/javascript"></script>
        <script src="/vendor/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
        <script src="/vendor/angular-bootstrap/ui-bootstrap.min.js" type="text/javascript"></script>
        <script src="/vendor/angular-grid/build/ng-grid.min.js" type="text/javascript"></script>
        <script src="/vendor/d3/d3.min.js" type="text/javascript"></script>
        <script src="/vendor/angular-charts/dist/angular-charts.min.js" type="text/javascript"></script>
        <script src="/scripts/app/controllers.js" type="text/javascript"></script>
    </body>
</html>